/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    exhibitions: Exhibition;
    submissions: Submission;
    'journal-articles': JournalArticle;
    'blog-posts': BlogPost;
    pages: Page;
    'press-mentions': PressMention;
    'jury-members': JuryMember;
    participants: Participant;
    media: Media;
    'private-media': PrivateMedia;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    exhibitions: ExhibitionsSelect<false> | ExhibitionsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'journal-articles': JournalArticlesSelect<false> | JournalArticlesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'press-mentions': PressMentionsSelect<false> | PressMentionsSelect<true>;
    'jury-members': JuryMembersSelect<false> | JuryMembersSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'private-media': PrivateMediaSelect<false> | PrivateMediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Competitions, personal and group exhibitions, and featured-artist showcases. The "Type" field controls which fields appear and how the public page behaves.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions".
 */
export interface Exhibition {
  id: number;
  title: string;
  /**
   * Page address, e.g. "open-call-colors" → curatone.art/exhibitions/open-call-colors
   */
  slug: string;
  /**
   * Competitions have an entry form and results. The other types are published manually.
   */
  type: 'competition' | 'personal' | 'group' | 'featured';
  /**
   * For competitions: "Open" shows the entry form; "Judging" hides it; "Closed" publishes the finalist gallery. IMPORTANT: setting "Closed" makes all works marked as finalists publicly visible.
   */
  status: 'open' | 'judging' | 'closed';
  /**
   * The main text shown on the page: theme of the competition or about-text of the exhibition.
   */
  theme?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  dates?: {
    start?: string | null;
    /**
     * Optional. Shown in the deadline schedule.
     */
    earlyDeadline?: string | null;
    /**
     * Optional. Shown in the deadline schedule.
     */
    regularDeadline?: string | null;
    /**
     * The countdown on the site runs to this date.
     */
    deadline?: string | null;
    resultsDate?: string | null;
  };
  /**
   * Which categories this competition accepts. Shown on the page and used by the entry form.
   */
  categories?:
    | (
        | 'painting'
        | 'drawing'
        | 'photography'
        | 'digital-art'
        | 'mixed-media'
        | 'illustration'
        | 'modern-art'
        | 'sculpture'
        | 'ceramics'
      )[]
    | null;
  /**
   * The artist this exhibition presents. Their name appears in the page heading.
   */
  artist?: (number | null) | Participant;
  /**
   * The works shown in this exhibition. For competitions this is not used — the results gallery is built from the competition's entries marked as finalists.
   */
  works?:
    | {
        /**
         * Upload before publishing — a striped placeholder is shown while empty.
         */
        image?: (number | null) | Media;
        title?: string | null;
        /**
         * For group exhibitions: shown under the work. For personal/featured: optional (the artist is already in the heading).
         */
        author?: (number | null) | Participant;
        year?: string | null;
        /**
         * E.g. "Oil on canvas".
         */
        medium?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. A short interview fragment shown on the exhibition page.
   */
  interviewExcerpt?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For featured artists: the competition the artist was recognised in.
   */
  relatedCompetition?: (number | null) | Exhibition;
  /**
   * Filled in manually after results, e.g. "214 works from 16 countries".
   */
  resultStats?: {
    worksCount?: number | null;
    countriesCount?: number | null;
  };
  /**
   * Marketing display only, e.g. "$15 – $25 per work". The actual charged amount is set below in "Payments".
   */
  feeNote?: string | null;
  /**
   * E.g. "Platinum · Gold · Silver + $100 prize".
   */
  awardsNote?: string | null;
  /**
   * Entry pricing. Not visible to editors.
   */
  payments?: {
    /**
     * 0 = free entry. If greater than 0, Stripe payment is required before an entry is accepted.
     */
    entryFee?: number | null;
    /**
     * 0 = none. If greater than 0, finalists pay this after results via a targeted payment link.
     */
    finalistFee?: number | null;
    currency?: ('usd' | 'eur') | null;
    /**
     * Secures the image links inside the judging CSV exports so jurors can view entries without accounts. Generated automatically; changing it invalidates previously exported links.
     */
    judgingToken?: string | null;
  };
  /**
   * While the competition is open or judging, author identities are never shown publicly.
   */
  hideAuthorsUntilResults?: boolean | null;
  /**
   * What Google shows in search results. Leave empty to use the title/description from above.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    seoTitle?: string | null;
    /**
     * Up to ~155 characters.
     */
    seoDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Public images: covers, published works, portraits, press logos. Everything here is visible to the whole internet. Competition entries are stored separately (privately) until results are published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description of the image for screen readers and SEO, e.g. "Oil painting of a coastal landscape".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * One record per person. Created automatically by the entry and article forms; the same person is reused across competitions and the journal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  name: string;
  /**
   * Address of the artist page, e.g. "anna-keller" → curatone.art/artists/anna-keller. Filled in automatically from the name.
   */
  slug?: string | null;
  email?: string | null;
  country?: string | null;
  /**
   * Optional. Used on the public artist page.
   */
  portrait?: (number | null) | Media;
  links?:
    | {
        /**
         * E.g. "Instagram", "Portfolio".
         */
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Awards, associations, achievements — written by the artist in the entry form. Shown publicly ONLY for finalists of published competitions.
   */
  aboutArtist?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  role?: ('participant' | 'jury' | 'admin' | 'member') | null;
  /**
   * Reserved for the future participant dashboard. Has no effect today.
   */
  profilePublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Works entered into competitions. To publish results: open a finished competition's entries, tick "Finalist" on the selected works (add award tier, score, citation), then set the competition status to "Closed". Non-finalist entries never become public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  competition: number | Exhibition;
  /**
   * Always stored, even while names are hidden for blind judging.
   */
  author: number | Participant;
  title?: string | null;
  category?:
    | (
        | 'painting'
        | 'drawing'
        | 'photography'
        | 'digital-art'
        | 'mixed-media'
        | 'illustration'
        | 'modern-art'
        | 'sculpture'
        | 'ceramics'
      )
    | null;
  /**
   * E.g. "Oil on canvas". Shown on the winner page.
   */
  medium?: string | null;
  year?: string | null;
  /**
   * E.g. "80 × 60 cm". Optional.
   */
  dimensions?: string | null;
  /**
   * Optional text about this specific work.
   */
  statement?: string | null;
  /**
   * Stored privately. If this entry becomes a finalist, the image is copied to public storage automatically when results are published.
   */
  image?: (number | null) | PrivateMedia;
  /**
   * Created automatically when results are published. Only edit to replace with a better-quality version.
   */
  publicImage?: (number | null) | Media;
  /**
   * Tick to include this work in the public results gallery once the competition is closed.
   */
  isFinalist?: boolean | null;
  awardTier?: ('platinum' | 'gold' | 'silver') | null;
  score?: number | null;
  /**
   * A short jury comment shown on the winner page.
   */
  juryCitation?: string | null;
  /**
   * E.g. "CTA-2026-0147". Used by the public certificate verification page.
   */
  certificateNumber?: string | null;
  /**
   * Address of the winner page, e.g. curatone.art/winners/anna-keller-tidelines. Generated automatically.
   */
  slug?: string | null;
  submittedAt?: string | null;
  payment?: {
    entryPaid?: boolean | null;
    finalistFeePaid?: boolean | null;
    stripeSessionId?: string | null;
    /**
     * Secures the targeted finalist payment link. To request the finalist fee, email the artist this link: <site>/pay/finalist/<entry id>?t=<this token>
     */
    payToken?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Private storage: competition entries during the entry/judging period and journal manuscript files. NOT visible to the public. Finalist images are copied to public Images automatically when results are published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-media".
 */
export interface PrivateMedia {
  id: number;
  /**
   * Optional note about the file.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Articles of the Curatone Art & Research Journal (ISSN 3054-6621). New submissions from the site arrive with status "Submitted". After off-platform peer review, set the status manually. Only "Published" articles appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-articles".
 */
export interface JournalArticle {
  id: number;
  title: string;
  /**
   * curatone.art/journal/<slug>
   */
  slug: string;
  /**
   * Peer review happens off-platform. Set "Published" only for reviewed, approved articles.
   */
  status: 'submitted' | 'under-review' | 'accepted' | 'rejected' | 'published';
  /**
   * The same person record used for competitions.
   */
  author: number | Participant;
  /**
   * How the author line appears on the site, e.g. "M. Keller, A. Osei". Leave empty to use the author's name.
   */
  authorsDisplay?: string | null;
  affiliation?: string | null;
  /**
   * Optional, e.g. 0000-0002-1825-0097.
   */
  orcid?: string | null;
  articleType?: ('research' | 'expert-insight' | 'visual-essay' | 'interview') | null;
  abstract?: string | null;
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  fullText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * One reference per row; numbered automatically on the page.
   */
  references?:
    | {
        reference: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The file the author submitted. Never public.
   */
  uploadedFile?: (number | null) | PrivateMedia;
  /**
   * Optional. The final typeset PDF offered for download on the article page.
   */
  publishedPdf?: (number | null) | Media;
  coverLetter?: string | null;
  /**
   * E.g. 10.63653/CTAR.2026.14
   */
  doi?: string | null;
  volume?: string | null;
  issue?: string | null;
  publishedDate?: string | null;
  licenseAgreed?: boolean | null;
  originalityConfirmed?: boolean | null;
  certificate?: {
    certificateIssued?: boolean | null;
    certificatePaid?: boolean | null;
    /**
     * Price of the publication certificate for this article.
     */
    certificateFee?: number | null;
    stripeSessionId?: string | null;
    /**
     * To offer the paid certificate, email the author this link: <site>/pay/certificate/<article id>?t=<this token>
     */
    payToken?: string | null;
  };
  /**
   * What Google shows in search results. Leave empty to use the title/description from above.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    seoTitle?: string | null;
    /**
     * Up to ~155 characters.
     */
    seoDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Editorial articles and news. Use "Save draft" while writing; only published posts appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * curatone.art/blog/<slug>
   */
  slug: string;
  /**
   * Displayed byline, e.g. "Curatone Editorial".
   */
  authorName?: string | null;
  /**
   * Short summary shown on the blog index.
   */
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Used as filter chips on the blog page, e.g. "For artists", "Competitions".
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedDate?: string | null;
  /**
   * Inserts a banner inviting readers to the current open competition.
   */
  showOpenCallCta?: boolean | null;
  /**
   * What Google shows in search results. Leave empty to use the title/description from above.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    seoTitle?: string | null;
    /**
     * Up to ~155 characters.
     */
    seoDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Static pages: About, Rules, Contact, legal pages. The page address is curatone.art/<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * curatone.art/<slug>, e.g. "about", "impressum". Never use the word "visa" in slugs or content.
   */
  slug: string;
  /**
   * Optional lead paragraph under the heading.
   */
  intro?: string | null;
  /**
   * The page body, split into sections. Each section can have an optional heading.
   */
  sections?:
    | {
        heading?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What Google shows in search results. Leave empty to use the title/description from above.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    seoTitle?: string | null;
    /**
     * Up to ~155 characters.
     */
    seoDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * External articles about Curatone. Shown as a logo strip on the homepage and listed on the Press page. Links go to the external site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-mentions".
 */
export interface PressMention {
  id: number;
  /**
   * E.g. "ArtDaily".
   */
  publication: string;
  /**
   * Optional. If empty, the publication name is shown as styled text.
   */
  logo?: (number | null) | Media;
  articleTitle?: string | null;
  date?: string | null;
  url: string;
  /**
   * Lower numbers appear first in the homepage strip.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The public jury roster. "Display order" controls sorting — lower numbers appear first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jury-members".
 */
export interface JuryMember {
  id: number;
  name: string;
  /**
   * curatone.art/jury/<slug>
   */
  slug?: string | null;
  /**
   * Aspect ratio 3:4 works best.
   */
  photo?: (number | null) | Media;
  /**
   * E.g. "Creative director", "Oil painter".
   */
  role?: string | null;
  /**
   * E.g. "China" or "Miami, USA".
   */
  country?: string | null;
  /**
   * One or two sentences shown on jury cards, e.g. "Fifteen years in visual design; recipient of nearly 100 international design awards."
   */
  shortCredential?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Competitions this juror served on. Shown as a table on the juror page.
   */
  judgingRecord?: (number | Exhibition)[] | null;
  memberSince?: string | null;
  /**
   * Ticked = shown in the prominent "Current jury" section. Unticked members still appear in the full roster with no change to how they are presented — this flag controls the current panel only, never seniority or validity.
   */
  active?: boolean | null;
  /**
   * Internal membership record. Informational storage only — dates are tracked manually by the owner (off-platform). Not visible to editors and never shown on the public site.
   */
  membership?: {
    tier?: ('jury' | 'expert') | null;
    start?: string | null;
    end?: string | null;
  };
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * The homepage jury band shows the first four jurors with this ticked.
   */
  showOnHomepage?: boolean | null;
  /**
   * Ticked members also appear on the Editorial Board page of the journal.
   */
  onEditorialBoard?: boolean | null;
  /**
   * Institution shown on the editorial board list, e.g. "Berlin University of the Arts".
   */
  affiliation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can log into this admin panel. "Admin" has full access; "Editor" can manage content but not payments, pricing, users, or deletion.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Editors cannot see payment data, change prices, manage users, or delete records.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'exhibitions';
        value: number | Exhibition;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'journal-articles';
        value: number | JournalArticle;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'press-mentions';
        value: number | PressMention;
      } | null)
    | ({
        relationTo: 'jury-members';
        value: number | JuryMember;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'private-media';
        value: number | PrivateMedia;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions_select".
 */
export interface ExhibitionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  status?: T;
  theme?: T;
  coverImage?: T;
  dates?:
    | T
    | {
        start?: T;
        earlyDeadline?: T;
        regularDeadline?: T;
        deadline?: T;
        resultsDate?: T;
      };
  categories?: T;
  artist?: T;
  works?:
    | T
    | {
        image?: T;
        title?: T;
        author?: T;
        year?: T;
        medium?: T;
        description?: T;
        id?: T;
      };
  interviewExcerpt?: T;
  relatedCompetition?: T;
  resultStats?:
    | T
    | {
        worksCount?: T;
        countriesCount?: T;
      };
  feeNote?: T;
  awardsNote?: T;
  payments?:
    | T
    | {
        entryFee?: T;
        finalistFee?: T;
        currency?: T;
        judgingToken?: T;
      };
  hideAuthorsUntilResults?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  competition?: T;
  author?: T;
  title?: T;
  category?: T;
  medium?: T;
  year?: T;
  dimensions?: T;
  statement?: T;
  image?: T;
  publicImage?: T;
  isFinalist?: T;
  awardTier?: T;
  score?: T;
  juryCitation?: T;
  certificateNumber?: T;
  slug?: T;
  submittedAt?: T;
  payment?:
    | T
    | {
        entryPaid?: T;
        finalistFeePaid?: T;
        stripeSessionId?: T;
        payToken?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-articles_select".
 */
export interface JournalArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  author?: T;
  authorsDisplay?: T;
  affiliation?: T;
  orcid?: T;
  articleType?: T;
  abstract?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  fullText?: T;
  references?:
    | T
    | {
        reference?: T;
        id?: T;
      };
  uploadedFile?: T;
  publishedPdf?: T;
  coverLetter?: T;
  doi?: T;
  volume?: T;
  issue?: T;
  publishedDate?: T;
  licenseAgreed?: T;
  originalityConfirmed?: T;
  certificate?:
    | T
    | {
        certificateIssued?: T;
        certificatePaid?: T;
        certificateFee?: T;
        stripeSessionId?: T;
        payToken?: T;
      };
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  authorName?: T;
  excerpt?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  body?: T;
  publishedDate?: T;
  showOpenCallCta?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-mentions_select".
 */
export interface PressMentionsSelect<T extends boolean = true> {
  publication?: T;
  logo?: T;
  articleTitle?: T;
  date?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jury-members_select".
 */
export interface JuryMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  role?: T;
  country?: T;
  shortCredential?: T;
  bio?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  judgingRecord?: T;
  memberSince?: T;
  active?: T;
  membership?:
    | T
    | {
        tier?: T;
        start?: T;
        end?: T;
      };
  order?: T;
  showOnHomepage?: T;
  onEditorialBoard?: T;
  affiliation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  email?: T;
  country?: T;
  portrait?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  aboutArtist?: T;
  role?: T;
  profilePublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-media_select".
 */
export interface PrivateMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Texts and numbers on the homepage. The open calls, recent awards, exhibitions, jury and journal sections update automatically from their collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    lede?: string | null;
    /**
     * The competition shown in the hero card and the featured open-call block. If empty, the open competition with the nearest deadline is used.
     */
    featuredCompetition?: (number | null) | Exhibition;
  };
  /**
   * The row of numbers under the hero, e.g. "5+ / Competitions concluded".
   */
  stats?:
    | {
        /**
         * E.g. "5+", "850+".
         */
        value: string;
        /**
         * E.g. "Competitions concluded".
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Quotes from winners, shown under "Recent awards". The first two are displayed.
   */
  testimonials?:
    | {
        quote: string;
        name: string;
        /**
         * E.g. "Winner, Colors 2025".
         */
        attribution?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lede?: T;
        featuredCompetition?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        attribution?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}